[package]
name = "wye"
version = "1.0.0"
edition = "2021"

[dependencies]
lalrpop = "0.20.2"
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }
ordered-float = "4.2.1"

[build-dependencies]
lalrpop = "0.20.2"
