[package]
name = "wye"
version = "2.0.0"
edition = "2021"

[dependencies]
codespan-reporting = "0.11.1"
lalrpop = "0.22.0"
lalrpop-util = { version = "0.22.0", features = ["lexer", "unicode"] }
ordered-float = "4.2.1"

[build-dependencies]
lalrpop = "0.22.0"
